version: '3.8'

services:
  mysql:
    image: mysql:8.0.40
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend  # Path to the backend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql
      - DB_USER=admin
      - DB_PASS=password
      - DB_NAME=todo_db
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend  # Path to the frontend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
